import { Activity, Contact, PendingSettlement } from "./constants";

export const contacts: Contact[] = [
  {
    id: "1",
    name: "Rahul Sharma",
    phone: "+91 9876543210",
    onApp: true,
    avatarUri: "https://i.pravatar.cc/150?img=1",
    isSelected: false,
  },
  {
    id: "2",
    name: "Priya Gupta",
    phone: "+91 9123456789",
    onApp: true,
    avatarUri: "https://i.pravatar.cc/150?img=5",
    isSelected: false,
  },
  {
    id: "3",
    name: "Amit Verma",
    phone: "+91 9988776655",
    onApp: false,
    isSelected: false,
  },
  {
    id: "4",
    name: "Sneha Kapoor",
    phone: "+91 9871234567",
    onApp: true,
    avatarUri: "https://i.pravatar.cc/150?img=12",
    isSelected: false,
  },
  {
    id: "5",
    name: "Mohammad Emad",
    phone: "+91 9012345678",
    onApp: false,
    isSelected: false,
  },
  {
    id: "6",
    name: "Rohit Singh",
    phone: "+91 9870011223",
    onApp: true,
    isSelected: false,
  },
  {
    id: "7",
    name: "Anjali Mehta",
    phone: "+91 9001122334",
    onApp: false,
    avatarUri: "https://i.pravatar.cc/150?img=32",
    isSelected: false,
  },
  {
    id: "8",
    name: "Aditya Kumar",
    phone: "+91 8899776655",
    onApp: true,
    avatarUri: "https://i.pravatar.cc/150?img=22",
    isSelected: false,
  },
  {
    id: "9",
    name: "Neha Agarwal",
    phone: "+91 9765432109",
    onApp: false,
    isSelected: false,
  },
  {
    id: "10",
    name: "Vikram Malhotra",
    phone: "+91 9811122233",
    onApp: true,
    isSelected: false,
  },
];


export const recentActivities: Activity[] = [
	{
		id: "1",
		title: "Dinner at Toit",
		groupName: "Goa Trip",
		paidBy: "you",
		amount: 540,
		balanceType: "receivable",
		timeAgo: "2h",
		category: "Food",
	},
	{
		id: "2",
		title: "Uber to airport",
		groupName: "Goa Trip",
		paidBy: "Rahul",
		amount: 180,
		balanceType: "payable",
		timeAgo: "1d",
		category: "Travel",
	},
	{
		id: "3",
		title: "Weekly groceries",
		groupName: "Flatmates",
		paidBy: "you",
		amount: 820,
		balanceType: "receivable",
		timeAgo: "2d",
		category: "Grocery",
	},
	{
		id: "4",
		title: "Electricity bill",
		groupName: "Flatmates",
		paidBy: "Sneha",
		amount: 420,
		balanceType: "payable",
		timeAgo: "3d",
		category: "Utility",
	},
	{
		id: "5",
		title: "Movie tickets",
		groupName: "Friends",
		paidBy: "Aman",
		amount: 250,
		balanceType: "payable",
		timeAgo: "5d",
		category: "Entertainment",
	},
	{
		id: "6",
		title: "Pizza Night",
		groupName: "Friends",
		paidBy: "you",
		amount: 360,
		balanceType: "receivable",
		timeAgo: "1w",
		category: "Food",
	},
];

export const pendingSettlements: PendingSettlement[] = [
	{
		id: "1",
		username: "Rahul Verma",
		balanceType: "receivable",
		amount: 420,
	},
	{
		id: "2",
		username: "Sneha Lyer",
		balanceType: "payable",
		amount: 180,
	},
];